import mongoose from 'mongoose'
import app from '../../src/app'
import server from '../../src/index'
import supertest from 'supertest'
import testDataGenerator from '../utils/testDataGenerator'
describe("Testing Video Routes", () => {

    const request = supertest(app)
    const contentType: string = "application/json"

    beforeEach(async () => {
        await testDataGenerator.generateData()
    })

    test("GET Videos", async () => {

        const response = await request.get('/videos')
        expect(response.statusCode).toBe(200)
        expect(response.body).toBeTruthy()
        expect(response.type).toBe(contentType)
        expect(response.body).toBeInstanceOf(Array)
    })

    test("GET Video by Id", async () => {

        const allVideos = await request.get('/videos')
        const videoId = allVideos.body[0]._id
        const response = await request.get(`/videos/${videoId}`)

        expect(response.statusCode).toBe(200)
        expect(response.body).toBeTruthy()
        expect(response.type).toBe(contentType)
    })

    test("GET Video by Id with a non existing Id", async () => {

        const videoId = "62a6a9bddc5026ae2492d9ef"
        const response = await request.get(`/videos/${videoId}`)

        expect(response.statusCode).toBe(204)
    })


    test("POST Videos", async () => {

        const newVideo = {
            "title": "Vitest vs Jest",
            "description": "why Vitest could be better",
            "url": "https://www.youtube.com/watch?v=7f-71kYhK00"
        }

        const response = await request.post('/videos').send(newVideo)
        expect(response.statusCode).toBe(200)
    })

    test("Create already existing Videos", async () => {

        const newVideo = {
            "title": "Vitest vs Jest",
            "description": "why Vitest could be better",
            "url": "https://www.youtube.com/watch?v=7f-71kYhK00"
        }

        const newVideo2 = {
            "title": "Vitest vs Jest",
            "description": "why Vitest could be better",
            "url": "https://www.youtube.com/watch?v=7f-71kYhK00"
        }

        await request.post('/videos').send(newVideo)

        const response = await request.post('/videos').send(newVideo2)
        expect(response.statusCode).toBe(301)
        expect(response.body).toStrictEqual({message: 'The URL already exists'})
    })

    test("PUT Video by Id", async () => {

        const allVideos = await request.get('/videos')
        const videoId = allVideos.body[0]._id
        const newVideo = {
            "title": "Infinite Procedurally Generated Djent",
            "description": "This djent is generated by IA",
            "url": "https://www.youtube.com/watch?v=8OR7mO2L5Kw"
        }
        const response = await request.put(`/videos/${videoId}`).send(newVideo)

        expect(response.statusCode).toBe(200)
        expect(response.body).toBeTruthy()
        expect(response.body.url).toBe(newVideo.url)
    })

    test("PUT Video by Id that doesn't exist", async () => {

        const videoId = "62a6a9bddc5026ae2492d9ef"
        const newVideo = {
            "title": "Infinite Procedurally Generated Djent",
            "description": "This djent is generated by IA",
            "url": "https://www.youtube.com/watch?v=8OR7mO2L5Kw"
        }
        const response = await request.put(`/videos/${videoId}`).send(newVideo)

        expect(response.statusCode).toBe(204)
    })

    test("DELETE Video by Id", async () => {

        const allVideos = await request.get('/videos')
        const videoId = allVideos.body[0]._id

        const response = await request.delete(`/videos/${videoId}`)

        expect(response.statusCode).toBe(200)
    })


    test("DELETE Video by Id that doesn't exist", async () => {

        const videoId = "62a6a9bddc5026ae2492d9ef"
        const response = await request.delete(`/videos/${videoId}`)

        expect(response.statusCode).toBe(204)
    })

    afterAll(() => {
        mongoose.connection.close()
        server.close()
    })
})